!-----------------------------------------------------------------------------------------------------------------------
! Type220 FlowDesigner Sensor Data File Reader
!-----------------------------------------------------------------------------------------------------------------------    
      Subroutine Type220

! Object: FLowDesigner Sensor Data Reader
! Simulation Studio Model: Type220SensorData
! 

! Author: YY
! Editor: YY
! Date:	 7月 31, 2013
! last modified: 7月 31, 2013
! 
! 
! *** 
! *** Model Parameters 
! *** 
!			Interval Time	- [0;+Inf]
!           StartTime - [0;+Inf]
!           StopTime - [0;+Inf]
!			LU for the Sensor data file	- [30;+Inf]
!			Number of Sensors	- [0;+Inf]
!           Delete the sensor file - [0;1]

! *** 
! *** Model Inputs 
! *** 

! *** 
! *** Model Outputs 
! *** 
!			elapsed time	s [0;+Inf]
!			Wx	mm [0;+Inf]
!			Wy	mm [0;+Inf]
!			Wz	mm [0;+Inf]
!			U	m/s [-Inf;+Inf]
!			V	m/s [-Inf;+Inf]
!			W	m/s [-Inf;+Inf]
!			P	Pa [-Inf;+Inf]
!			T	C [-Inf;+Inf]
!			Cc	- [-Inf;+Inf]
!			Ch	- [0;+Inf]
!			C1	- [-Inf;+Inf]
!			C2	- [-Inf;+Inf]
!			C3	- [-Inf;+Inf]

! *** 
! *** Model Derivatives 
! *** 

! (Comments and routine interface generated by TRNSYS Studio)
!************************************************************************

!-----------------------------------------------------------------------------------------------------------------------
! This TRNSYS component skeleton was generated from the TRNSYS studio based on the user-supplied parameters, inputs, 
! outputs, and derivatives.  The user should check the component formulation carefully and add the content to transform
! the parameters, inputs and derivatives into outputs.  Remember, outputs should be the average value over the timestep
! and not the value at the end of the timestep; although in many models these are exactly the same values.  Refer to 
! existing types for examples of using advanced features inside the model (Formats, Labels etc.)
!-----------------------------------------------------------------------------------------------------------------------


      Use TrnsysConstants
      Use TrnsysFunctions

!-----------------------------------------------------------------------------------------------------------------------

!DEC$Attributes DLLexport :: Type220

!-----------------------------------------------------------------------------------------------------------------------
!Trnsys Declarations
      Implicit None

      Double Precision Timestep,Time
      Integer CurrentUnit,CurrentType


!    PARAMETERS
      !DOUBLE PRECISION Interval_Time
      !DOUBLE PRECISION LU
      !DOUBLE PRECISION NumOfSensors
      INTEGER Interval_Time
      DOUBLE PRECISION StartTime
      DOUBLE PRECISION StopTime      
      INTEGER LU
      INTEGER NumOfSensors
      INTEGER DeleteSensorFile

!    INPUTS

      !作業用変数
      Character(len=maxPathLength) filename !name of sensor data file
      Logical FileLoaded
      Logical exists
      INTEGER numOfOutputs
      INTEGER i,j,k

      
      
      Character*32 ID !variables read from the data file
      DOUBLE PRECISION:: ElapsedTime=0.0d0
      INTEGER NumberOfSensors
      Character*32 Label
      DOUBLE PRECISION Wx(99), Wy(99), Wz(99) !センサーのx,y,z方向の幅
      DOUBLE PRECISION U(99), V(99), W(99), P(99), T(99), Cc(99), Ch(99), C1(99), C2(99), C3(99)
      
      

      Character(len=maxmessagelength) ReadError,EndError,FoundError     !error messages generated by this component.
      
      Data FoundError/'The data file could not be opened. Please check that the filename and path are correct.'/
      Data ReadError/'An error occurred while reading the data file. Please check that the data file has the correct format.'/
      Data EndError/'The end of the data file was encountered while reading. Please check that the data file has the correct format.'/

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Get the Global Trnsys Simulation Variables
      Time=getSimulationTime()
      Timestep=getSimulationTimeStep()
      CurrentUnit = getCurrentUnit()
      CurrentType = getCurrentType()
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Version Number for This Type
      If(getIsVersionSigningTime()) Then
		Call SetTypeVersion(17)
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do Any Last Call Manipulations Here
      If(getIsLastCallofSimulation()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Perform Any "After Convergence" Manipulations That May Be Required at the End of Each Timestep
      If(getIsEndOfTimestep()) Then
          
        ! StartTime,StopTimeの範囲外であれば、コントロールファイルの書き出しは行わず終了
        if((time < StartTime) .or. (StopTime < time)) return 
        
        if(DeleteSensorFile == 1) then
          !sensor data fileを削除する
          LU = jfix(getParameterValue(4)+0.1)
          filename = getLUFilename(LU)
          Open (unit=LU,file=filename,action='READ',status='OLD',err=402)
          Close (LU, status='delete')
#ifdef debug          
          Call Messages(-1,'The sensor file has been deleted.','Notice',CurrentUnit,CurrentType)
#endif
        endif
		
        Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the "Very First Call of the Simulation Manipulations" Here
      If(getIsFirstCallofSimulation()) Then
          
        NumOfSensors = jfix(getParameterValue(5)+0.1)
        numOfOutputs = 1+NumOfSensors*13

		!Tell the TRNSYS Engine How This Type Works
		Call SetNumberofParameters(6)           !The number of parameters that the the model wants
		Call SetNumberofInputs(0)                   !The number of inputs that the the model wants
		Call SetNumberofDerivatives(0)         !The number of derivatives that the the model wants
		Call SetNumberofOutputs(numOfOutputs)                 !The number of outputs that the the model produces
		Call SetIterationMode(1)                             !An indicator for the iteration mode (default=1).  Refer to section 8.4.3.5 of the documentation for more details.
		Call SetNumberStoredVariables(0,0)                   !The number of static variables that the model wants stored in the global storage array and the number of dynamic variables that the model wants stored in the global storage array
		Call SetNumberofDiscreteControls(0)               !The number of discrete control functions set by this model (a value greater than zero requires the user to use Solver 1: Powell's method)

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the First Timestep Manipulations Here - There Are No Iterations at the Intial Time
      If (getIsStartTime()) Then
      Interval_Time = jfix(getParameterValue(1)+0.1) ! sensor dataの再チェックまでの待機時間[msec]
      StartTime = getParameterValue(2)               ! 読み込み処理の開始時間[h]
      StopTime  = getParameterValue(3)               ! 読み込み処理の終了時間[h]
      LU            = jfix(getParameterValue(4)+0.1) ! sensor data のLUを取得
      NumOfSensors  = jfix(getParameterValue(5)+0.1)
      DeleteSensorFile = jfix(getParameterValue(6)+0.1)



	
   !Check the Parameters for Problems (#,ErrorType,Text)
   !Sample Code: If( PAR1 <= 0.) Call FoundBadParameter(1,'Fatal','The first parameter provided to this model is not acceptable.')

   !Set the Initial Values of the Outputs (#,Value)
		Call SetOutputValue(1, 0) ! elapsed time
        do i = 1, NumOfSensors
		    Call SetOutputValue((i-1)*13+2, 0.0d0) ! Wx
		    Call SetOutputValue((i-1)*13+3, 0.0d0) ! Wy
		    Call SetOutputValue((i-1)*13+4, 0.0d0) ! Wz
		    Call SetOutputValue((i-1)*13+5, 0.0d0) ! U
		    Call SetOutputValue((i-1)*13+6, 0.0d0) ! V
		    Call SetOutputValue((i-1)*13+7, 0.0d0) ! W
		    Call SetOutputValue((i-1)*13+8, 0.0d0) ! P
		    Call SetOutputValue((i-1)*13+9, 0.0d0) ! T
		    Call SetOutputValue((i-1)*13+10, 0.0d0) ! Cc
		    Call SetOutputValue((i-1)*13+11, 0.0d0) ! Ch
		    Call SetOutputValue((i-1)*13+12, 0.0d0) ! C1
		    Call SetOutputValue((i-1)*13+13, 0.0d0) ! C2
		    Call SetOutputValue((i-1)*13+14, 0.0d0) ! C3
        enddo

   !If Needed, Set the Initial Values of the Static Storage Variables (#,Value)
   !Sample Code: SetStaticArrayValue(1,0.d0)

   !If Needed, Set the Initial Values of the Dynamic Storage Variables (#,Value)
   !Sample Code: Call SetDynamicArrayValueThisIteration(1,20.d0)

   !If Needed, Set the Initial Values of the Discrete Controllers (#,Value)
   !Sample Code for Controller 1 Set to Off: Call SetDesiredDiscreteControlState(1,0) 

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!ReRead the Parameters if Another Unit of This Type Has Been Called Last
      If(getIsReReadParameters()) Then
		!Read in the Values of the Parameters from the Input File
      Interval_Time = jfix(getParameterValue(1)+0.1) ! sensor dataの再チェックまでの待機時間[msec]
      StartTime = getParameterValue(2)               ! 読み込み処理の開始時間[h]
      StopTime  = getParameterValue(3)               ! 読み込み処理の終了時間[h]
      LU            = jfix(getParameterValue(4)+0.1) ! sensor data のLUを取得
      NumOfSensors  = jfix(getParameterValue(5)+0.1)
      DeleteSensorFile = jfix(getParameterValue(6)+0.1)
		
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!Read the Inputs
		

	!Check the Inputs for Problems (#,ErrorType,Text)
	!Sample Code: If( IN1 <= 0.) Call FoundBadInput(1,'Fatal','The first input provided to this model is not acceptable.')
 
      If(ErrorFound()) Return
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!    *** PERFORM ALL THE CALCULATION HERE FOR THIS MODEL. ***
!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Previous Control States if Discrete Controllers are Being Used (#)
	!Sample Code: CONTROL_LAST=getPreviousControlState(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Values from the Global Storage Array for the Static Variables (#)
	!Sample Code: STATIC1=getStaticArrayValue(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Initial Values of the Dynamic Variables from the Global Storage Array (#)
	!Sample Code: T_INITIAL_1=getDynamicArrayValueLastTimestep(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!Perform All of the Calculations Here to Set the Outputs from the Model Based on the Inputs

	!Sample Code: OUT1=IN1+PAR1

	!If the model requires the solution of numerical derivatives, set these derivatives and get the current solution
	!Sample Code: T1=getNumericalSolution(1)
	!Sample Code: T2=getNumericalSolution(2)
	!Sample Code: DTDT1=3.*T2+7.*T1-15.
	!Sample Code: DTDT2=-2.*T1+11.*T2+21.
	!Sample Code: Call SetNumericalDerivative(1,DTDT1)
	!Sample Code: Call SetNumericalDerivative(2,DTDT2)

      ! FlowDesigner sensor data file is exist?

      !if(NumOfSensors >1) then
      !    Call Messages(-1,'This version does not support several sensors. Please set the num of sensors to 1.','fatal',CurrentUnit,CurrentType)
      !    return
      !endif

      ! StartTime,StopTimeの範囲外であれば、コントロールファイルの書き出しは行わず終了
      if((time < StartTime) .or. (StopTime < time)) return 
        
        
      FileLoaded = .FALSE.
      do while (FileLoaded == .FALSE.) !sensor data fileを読み終えるまでループする
          
          filename = getLUFilename(LU)
          INQUIRE (FILE = filename, EXIST = exists) 
          if(.NOT. exists) then
#ifdef debug
            Call Messages(-1,'The sensor file does not exists.','Notice',CurrentUnit,CurrentType)
#endif
            goto 200
          endif
          
          !----------------------------------------
          !sensor data fileを開く
          !----------------------------------------
          Open (unit=LU,file=filename,action='READWRITE',status='OLD',err=200)
          
#ifdef debug
          Call Messages(-1,'The sensor file has been found.','Notice',CurrentUnit,CurrentType)
#endif
          Rewind (LU)
          
          ! Read the values from the sensor data
          Read(lu,*,err=400,end=401) ID
          Read(lu,*,err=400,end=401) ElapsedTime
          Read(lu,*,err=400,end=401) NumberOfSensors 
          
          ! sensor data fileとパラメーターのセンサ数が違っていたらエラー処理
          if(NumberOfSensors /= NumOfSensors) then
            Call Messages(-1,'The number of sensors in the file does not match the parameter.','fatal',CurrentUnit,CurrentType)
            return
          endif
          
          !Read(lu,*,err=400,end=401) Label
          
          do i=1, NumOfSensors
            Read(lu,*,err=400,end=401) Label !TRNSYSでは使うところが無いので、読み飛ばす
            Read(lu,*,err=400,end=401) Wx(i), Wy(i), Wz(i)
            Read(lu,*,err=400,end=401) U(i), V(i), W(i), P(i), T(i), Cc(i), Ch(i), C1(i), C2(i), C3(i)
          enddo
          
          Close(LU)
          

          
          
          FileLoaded = .TRUE.
          !goto 100 ! ファイル処理が終了したのでループを抜ける
          exit
          
          !----------------------------------------
          !sensor data が無ければ所定の時間待機する
          !----------------------------------------
200       CALL SLEEPQQ(Interval_Time)     
          Call DoEvents() !Windowsイベントを処理する
#ifdef debug
          Call Messages(-1,'Waitting for the sensor file.','Notice',CurrentUnit,CurrentType)
#endif
          
      end do
      
100   continue

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Outputs from this Model (#,Value)

		Call SetOutputValue(1, ElapsedTime) ! elapsed time
        
        do i=1, NumOfSensors
		    Call SetOutputValue((i-1)*13+2, Wx(i)) ! Wx
		    Call SetOutputValue((i-1)*13+3, Wy(i)) ! Wy
		    Call SetOutputValue((i-1)*13+4, Wz(i)) ! Wz
		    Call SetOutputValue((i-1)*13+5, U(i)) ! U
		    Call SetOutputValue((i-1)*13+6, V(i)) ! V
		    Call SetOutputValue((i-1)*13+7, W(i)) ! W
		    Call SetOutputValue((i-1)*13+8, P(i)) ! P
		    Call SetOutputValue((i-1)*13+9, T(i)) ! T
		    Call SetOutputValue((i-1)*13+10, Cc(i)) ! Cc
		    Call SetOutputValue((i-1)*13+11, Ch(i)) ! Ch
		    Call SetOutputValue((i-1)*13+12, C1(i)) ! C1
		    Call SetOutputValue((i-1)*13+13, C2(i)) ! C2
		    Call SetOutputValue((i-1)*13+14, C3(i)) ! C3
        enddo
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Desired Disceret Control Signal Values for this Iteration (#,State)
!Sample Code:  Call SetDesiredDiscreteControlState(1,1)
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Final value of the Dynamic Variables in the Global Storage Array (#,Value)
!Sample Code:  Call SetValueThisIteration(1,T_FINAL_1)
!-----------------------------------------------------------------------------------------------------------------------
 
      Return
      
      
!-----------------------------------------------------------------------------------------------------------------------
! Error messages
!-----------------------------------------------------------------------------------------------------------------------
! Error found in reading data file
 400  Call Messages(-1,ReadError,'fatal',CurrentUnit,CurrentType)
      Return
 401  Call Messages(-1,EndError,'fatal',CurrentUnit,CurrentType)
      Return
 402  Call Messages(-1,FoundError,'fatal',CurrentUnit,CurrentType)
      Return
      
      
    End
!-----------------------------------------------------------------------------------------------------------------------
! イベント処理    
!-----------------------------------------------------------------------------------------------------------------------
SUBROUTINE DoEvents()

use IFWINTY
use USER32
use IFLOGM
logical lNotQuit, lret
integer iret
TYPE (T_MSG) mesg
lNotQuit = .TRUE.
do while (lNotQuit .AND. (PeekMessage(mesg, 0, 0, 0, PM_NOREMOVE) /= 0))
  lNotQuit = GetMessage(mesg, NULL, 0, 0)
    if (lNotQuit) then
      if (DLGISDLGMESSAGE(mesg) .EQV. .FALSE.) then
         lret = TranslateMessage(mesg)
         iret = DispatchMessage(mesg)
      end if
    end if
end do


END SUBROUTINE DoEvents