module subprogs
    
    Use TrnsysConstants
    Use TrnsysFunctions

    
!Trnsys Declarations
      Implicit None
      !
      !Double Precision _timestep,Time
      !Integer CurrentUnit,CurrentType
      !

      
!    PARAMETERS
      INTEGER Interval_Time
      DOUBLE PRECISION StartTime
      DOUBLE PRECISION StopTime
      INTEGER LU
      INTEGER Num_of_Flow_Control
      INTEGER Num_of_Surface_Control
      INTEGER Num_of_Volume_Control
      INTEGER Num_of_Open_Control
      INTEGER OverwriteFlag
      
!    INPUTS

    !FLOW_CONTROL
      DOUBLE PRECISION Flow_Control_Label(99)
      Character (len=maxDescripLength) :: FlowControlLabel(99)
      DOUBLE PRECISION U(99)
      DOUBLE PRECISION V(99)
      DOUBLE PRECISION W(99)
      DOUBLE PRECISION T(99)
      DOUBLE PRECISION Cc(99)
      DOUBLE PRECISION Ch(99)
      DOUBLE PRECISION C1(99)
      DOUBLE PRECISION C2(99)
      DOUBLE PRECISION C3(99)
      
    !SURFACE_CONTROL
      Character (len=maxDescripLength) Surface_Control_Label(99)
      DOUBLE PRECISION Tstar(99)
      DOUBLE PRECISION Mcsurf(99)
      DOUBLE PRECISION Mhsurf(99)
      DOUBLE PRECISION M1surf(99)
      DOUBLE PRECISION M2surf(99)
      DOUBLE PRECISION M3surf(99)
      
    !VOLUME_CONRTOL
      Character (len=maxDescripLength) Volume_Control_Label(99)
      DOUBLE PRECISION Q(99)
      DOUBLE PRECISION kx(99)
      DOUBLE PRECISION ky(99)
      DOUBLE PRECISION kz(99)
      DOUBLE PRECISION Mcvol(99)
      DOUBLE PRECISION Mhvol(99)
      DOUBLE PRECISION M1vol(99)
      DOUBLE PRECISION M2vol(99)
      DOUBLE PRECISION M3vol(99)
      
    !OPEN_CONTROL
      Character (len=maxDescripLength) Open_Control_Label(99)
      DOUBLE PRECISION r(99)
      
      !作業用変数
      INTEGER NumOfInputs
      INTEGER i,j,k
      INTEGER base
      Character(len=maxPathLength) filename !name of control data file
      Logical FileSaved
      Logical exists   
      !
      !! Error messages     
      !Character(len=maxmessagelength) FoundError, WriteError     !error messages generated by this component.
      !
      !Data FoundError/'The control file could not be opened. Please check that the filename and path are correct.'/
      !Data WriteError/'An error occurred while writing the control data file.'/
      
    contains
    !-------------------------------------------------------------------------------------------------------------------
    ! Control Data Fileの書き出し処理    
    !-------------------------------------------------------------------------------------------------------------------
    subroutine saveControlFile(CurrentUnit,CurrentType, Time, Timestep)
      Implicit None

      Double Precision Timestep,Time
      Integer CurrentUnit,CurrentType
      
      ! Error messages     
      Character(len=maxmessagelength) FoundError, WriteError     !error messages generated by this component.

      Data FoundError/'The control file could not be opened. Please check that the filename and path are correct.'/
      Data WriteError/'An error occurred while writing the control data file.'/
        
        !Get Parameters
        Interval_Time = jfix(getParameterValue(1)+0.1) !control dataの再チェックまでの待機時間[msec]
        StartTime = getParameterValue(2)
        StopTime  = getParameterValue(3)
        LU = jfix(getParameterValue(4)+0.1)
        ! Inputs数を計算
        Num_of_Flow_Control     = JFIX(getParameterValue(5)+0.1) 
        Num_of_Surface_Control  = JFIX(getParameterValue(6)+0.1)  
        Num_of_Volume_Control   = JFIX(getParameterValue(7)+0.1) 
        Num_of_Open_Control     = JFIX(getParameterValue(8)+0.1) 
        NumOfInputs = Num_of_Flow_Control*10 + Num_of_Surface_Control*7 + Num_of_Volume_Control*10 + Num_of_Open_Control*2
        OverwriteFlag           = JFIX(getParameterValue(9)+0.1) 


        !Flow_Control_Label
        if(Num_of_Flow_Control>0) then
            base=0
            do i=1, Num_of_Flow_Control
              FlowControlLabel(i) = getVariableDescription(CurrentUnit,(i-1)*10+1)
              U(i) = GetInputValue((i-1)*10+2)
              V(i) = GetInputValue((i-1)*10+3)
              W(i) = GetInputValue((i-1)*10+4)
              T(i) = GetInputValue((i-1)*10+5)
              Cc(i) = GetInputValue((i-1)*10+6)
              Ch(i) = GetInputValue((i-1)*10+7)
              C1(i) = GetInputValue((i-1)*10+8)
              C2(i) = GetInputValue((i-1)*10+9)
              C3(i) = GetInputValue((i-1)*10+10)
            enddo
        endif
        
        !Surface_Control_Label
        if(Num_of_Surface_Control>0) then
            base = Num_of_Flow_Control*10
            do i=1, Num_of_Surface_Control
              Surface_Control_Label(i) = getVariableDescription(CurrentUnit, base+(i-1)*7+1)
              Tstar(i) = GetInputValue(base+(i-1)*7+2)
              Mcsurf(i) = GetInputValue(base+(i-1)*7+3)
              Mhsurf(i) = GetInputValue(base+(i-1)*7+4)
              M1surf(i) = GetInputValue(base+(i-1)*7+5)
              M2surf(i) = GetInputValue(base+(i-1)*7+6)
              M3surf(i) = GetInputValue(base+(i-1)*7+7)
          enddo
        endif
        
        !Volume_Control_Label
        if(Num_of_Volume_Control>0) then
            base = Num_of_Flow_Control*10 + Num_of_Surface_Control*7
            do i=1, Num_of_Volume_Control        
              Volume_Control_Label(i) = getVariableDescription(CurrentUnit, base+(i-1)*10+1)
              Q(i) = GetInputValue(base+(i-1)*10+2)
              kx(i) = GetInputValue(base+(i-1)*10+3)
              ky(i) = GetInputValue(base+(i-1)*10+4)
              kz(i) = GetInputValue(base+(i-1)*10+5)
              Mcvol(i) = GetInputValue(base+(i-1)*10+6)
              Mhvol(i) = GetInputValue(base+(i-1)*10+7)
              M1vol(i) = GetInputValue(base+(i-1)*10+8)
              M2vol(i) = GetInputValue(base+(i-1)*10+9)
              M3vol(i) = GetInputValue(base+(i-1)*10+10)
             enddo
        endif
        
        
        !Open_Control_Label
        if(Num_of_Open_Control>0) then
            base = Num_of_Flow_Control*10 + Num_of_Surface_Control*7 + Num_of_Volume_Control*10 
            do i=1, Num_of_Open_Control            
              Open_Control_Label(i) = getVariableDescription(CurrentUnit, base+(i-1)*10+1)
              r(i) = GetInputValue(base+(i-1)*10+2)
             enddo
        endif
      
      ! StartTime,StopTimeの範囲外であれば、コントロールファイルの書き出しは行わず終了
      if((time < StartTime) .or. (StopTime < time)) return 
      
      ! Control Data Fileへの書き出し処理
      !------------------------------------
      FileSaved = .FALSE.
      do while (FileSaved == .FALSE.) !control data fileを書き終えるまでループする
      
        filename = getLUFilename(LU)
        INQUIRE (FILE = filename, EXIST = exists) 
        if(exists .and. (OverwriteFlag==0)) then
#ifdef debug
            Call Messages(-1,'The control file still exists.','Notice',CurrentUnit,CurrentType)
#endif
            goto 200
        endif
        
        if(OverwriteFlag == 1) then
            Open (unit=LU,file=filename,action='WRITE',status='REPLACE',err=402)
        else
            Open (unit=LU,file=filename,action='WRITE',status='NEW',err=402)
        endif
          
            
            !FLOW_CONTROL
            write(LU, '("FLOW_CONTROL")', err=400)
            write(LU, '(i0)', err=400) Num_of_Flow_Control
            
            if(Num_of_Flow_Control>0) then
                do i = 1, Num_of_Flow_Control
                    write(LU,'(A)' ,err=400) FlowControlLabel(i)
                    write(LU, '(9(f0.5, 1x))', err=400) U(i), V(i), W(i), T(i), Cc(i), Ch(i), C1(i), C2(i), C3(i)  
                enddo
            endif
           
            !SURFACE_CONTROL
            write(LU, '("SURFACE_CONTROL")', err=400)
            write(LU, '(i0)', err=400) Num_of_Surface_Control
            
            if(Num_of_Surface_Control>0) then
                do i = 1, Num_of_Surface_Control
                    write(LU, '(A)', err=400) Surface_Control_Label(i)
                    write(LU, '(6(f0.5, 1x))', err=400) Tstar(i), Mcsurf(i), Mhsurf(i), M1surf(i), M2surf(i), M3surf(i)
                enddo
            endif
           
            !VOLUME_CONTROL
            write(LU, '("VOLUME_CONTROL")', err=400)
            write(LU, '(i0)', err=400) Num_of_Volume_Control
            
            if(Num_of_Volume_Control>0) then
                do i = 1, Num_of_Volume_Control
                    write(LU, '(A)', err=400) Volume_Control_Label(i)
                    write(LU, '(9(f0.5, 1x))', err=400) Q(i), kx(i), ky(i), kz(i), Mcvol(i), Mhvol(i), M1vol(i), M2vol(i), M3vol(i)
                enddo
            endif
           
            !OPEN_CONTROL
            write(LU, '("OPEN_CONTROL")', err=400)
            write(LU, '(i0)', err=400) Num_of_Open_Control
            
            if(Num_of_Open_Control>0) then
                do i = 1, Num_of_Open_Control
                    write(LU, '(A)', err=400)  Open_Control_Label(i) 
                    write(LU, '(f0.5)', err=400) r(i)
                    
                enddo
            endif

            Close(LU)
            FileSaved = .TRUE.
            !ファイル処理が終了したのでループを抜ける
            exit
                  
                  
200       CALL SLEEPQQ(Interval_Time)     
          Call DoEvents() !Windowsイベントを処理する
#ifdef debug
          Call Messages(-1,'Waitting for removing the control file.','Notice',CurrentUnit,CurrentType)
#endif
      end do           
      
      return
!-----------------------------------------------------------------------------------------------------------------------
! Error messages
!-----------------------------------------------------------------------------------------------------------------------
! Error found in writing data file
400  Call Messages(-1,WriteError,'fatal',CurrentUnit,CurrentType) ! control data file書き込み中のエラー
      Return
 !401  Call Messages(-1,EndError,'fatal',CurrentUnit,CurrentType)
 !     Return
402 Call Messages(-1,FoundError,'fatal',CurrentUnit,CurrentType)
    
      Return      
    end subroutine saveControlFile
    end module subprogs
!-----------------------------------------------------------------------------------------------------------------------
! Type221 FlowDesigner Control Data File Writer
!-----------------------------------------------------------------------------------------------------------------------    
    Subroutine Type221

! Object: FLowDesigner Control Data Writer
! Simulation Studio Model: Type221ControlData
! 

! Author: YY
! Editor: YY
! Date:	 8月 02, 2013
! last modified: 8月 02, 2013
! 
! 
! *** 
! *** Model Parameters 
! *** 
!           Interval_Time
!           StartTime
!           StopTime
!			LU for the control file	- [30;+Inf]
!			Num of Flow Control	- [0;+Inf]
!			Num of Surface Control	- [0;+Inf]
!			Num of Volume Control	- [0;+Inf]
!			Num of Open Control	- [0;+Inf]

! *** 
! *** Model Inputs 
! *** 
!			Flow Control Label	- [-Inf;+Inf]
!			U	m/s [-Inf;+Inf]
!			V	m/s [-Inf;+Inf]
!			W	m/s [-Inf;+Inf]
!			T	C [-Inf;+Inf]
!			Cc	- [-Inf;+Inf]
!			Ch	- [0;+Inf]
!			C1	- [0;+Inf]
!			C2	- [0;+Inf]
!			C3	- [0;+Inf]
!			Surface Control Label	- [-Inf;+Inf]
!			Tstar	- [-Inf;+Inf]
!			Mc	- [-Inf;+Inf]
!			Mh	- [-Inf;+Inf]
!			M1	- [-Inf;+Inf]
!			M2	- [-Inf;+Inf]
!			M3	- [-Inf;+Inf]
!			Volume Control Label	- [-Inf;+Inf]
!			Q	- [-Inf;+Inf]
!			kx	- [-Inf;+Inf]
!			ky	- [-Inf;+Inf]
!			kz	- [-Inf;+Inf]
!			Mc	- [-Inf;+Inf]
!			Mh	- [-Inf;+Inf]
!			M1	- [-Inf;+Inf]
!			M2	- [-Inf;+Inf]
!			M3	- [-Inf;+Inf]
!			Open Control Label	- [-Inf;+Inf]
!			r	- [-Inf;+Inf]

! *** 
! *** Model Outputs 
! *** 

! *** 
! *** Model Derivatives 
! *** 

! (Comments and routine interface generated by TRNSYS Studio)
!************************************************************************

!-----------------------------------------------------------------------------------------------------------------------
! This TRNSYS component skeleton was generated from the TRNSYS studio based on the user-supplied parameters, inputs, 
! outputs, and derivatives.  The user should check the component formulation carefully and add the content to transform
! the parameters, inputs and derivatives into outputs.  Remember, outputs should be the average value over the timestep
! and not the value at the end of the timestep; although in many models these are exactly the same values.  Refer to 
! existing types for examples of using advanced features inside the model (Formats, Labels etc.)
!-----------------------------------------------------------------------------------------------------------------------


      Use TrnsysConstants
      Use TrnsysFunctions
      Use subprogs

!-----------------------------------------------------------------------------------------------------------------------

!DEC$Attributes DLLexport :: Type221

!-----------------------------------------------------------------------------------------------------------------------
!Trnsys Declarations
      Implicit None

      Double Precision Timestep,Time
      Integer CurrentUnit,CurrentType

!
!!    PARAMETERS
!      INTEGER Interval_Time
!      DOUBLE PRECISION StartTime
!      DOUBLE PRECISION StopTime
!      INTEGER LU
!      INTEGER Num_of_Flow_Control
!      INTEGER Num_of_Surface_Control
!      INTEGER Num_of_Volume_Control
!      INTEGER Num_of_Open_Control
!      INTEGER OverwriteFlag
!      
!!    INPUTS
!
!    !FLOW_CONTROL
!      DOUBLE PRECISION Flow_Control_Label(99)
!      Character (len=maxDescripLength) :: FlowControlLabel(99)
!      DOUBLE PRECISION U(99)
!      DOUBLE PRECISION V(99)
!      DOUBLE PRECISION W(99)
!      DOUBLE PRECISION T(99)
!      DOUBLE PRECISION Cc(99)
!      DOUBLE PRECISION Ch(99)
!      DOUBLE PRECISION C1(99)
!      DOUBLE PRECISION C2(99)
!      DOUBLE PRECISION C3(99)
!      
!    !SURFACE_CONTROL
!      Character (len=maxDescripLength) Surface_Control_Label(99)
!      DOUBLE PRECISION Tstar(99)
!      DOUBLE PRECISION Mcsurf(99)
!      DOUBLE PRECISION Mhsurf(99)
!      DOUBLE PRECISION M1surf(99)
!      DOUBLE PRECISION M2surf(99)
!      DOUBLE PRECISION M3surf(99)
!      
!    !VOLUME_CONRTOL
!      Character (len=maxDescripLength) Volume_Control_Label(99)
!      DOUBLE PRECISION Q(99)
!      DOUBLE PRECISION kx(99)
!      DOUBLE PRECISION ky(99)
!      DOUBLE PRECISION kz(99)
!      DOUBLE PRECISION Mcvol(99)
!      DOUBLE PRECISION Mhvol(99)
!      DOUBLE PRECISION M1vol(99)
!      DOUBLE PRECISION M2vol(99)
!      DOUBLE PRECISION M3vol(99)
!      
!    !OPEN_CONTROL
!      Character (len=maxDescripLength) Open_Control_Label(99)
!      DOUBLE PRECISION r(99)
!      
!      !作業用変数
!      INTEGER NumOfInputs
!      INTEGER i,j,k
!      INTEGER base
!      Character(len=maxPathLength) filename !name of control data file
!      Logical FileSaved
!      Logical exists
      
      ! Error messages
      Character(len=maxmessagelength) FoundError, WriteError, DeleteError     !error messages generated by this component.
      !Data FoundError/'The data file could not be opened. Please check that the filename and path are correct.'/
      Data FoundError/'The control file could not be opened. Please check that the filename and path are correct.'/
      Data WriteError/'An error occurred while writing the control data file.'/
      Data DeleteError/'An error occurred while deleting the control data file.'/
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Get the Global Trnsys Simulation Variables
      Time=getSimulationTime()
      Timestep=getSimulationTimeStep()
      CurrentUnit = getCurrentUnit()
      CurrentType = getCurrentType()
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Version Number for This Type
      If(getIsVersionSigningTime()) Then
		Call SetTypeVersion(17)
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do Any Last Call Manipulations Here
      If(getIsLastCallofSimulation()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Perform Any "After Convergence" Manipulations That May Be Required at the End of Each Timestep
      If(getIsEndOfTimestep()) Then

        Call saveControlFile(CurrentUnit,CurrentType, Time, Timestep)
 
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the "Very First Call of the Simulation Manipulations" Here
      If(getIsFirstCallofSimulation()) Then

        ! Inputs数を計算
        LU                      = jfix(getParameterValue(4)+0.1)
        Num_of_Flow_Control     = JFIX(getParameterValue(5)+0.1) 
        Num_of_Surface_Control  = JFIX(getParameterValue(6)+0.1)  
        Num_of_Volume_Control   = JFIX(getParameterValue(7)+0.1) 
        Num_of_Open_Control     = JFIX(getParameterValue(8)+0.1) 
        NumOfInputs = Num_of_Flow_Control*10 + Num_of_Surface_Control*7 + Num_of_Volume_Control*10 + Num_of_Open_Control*2
        OverwriteFlag           = JFIX(getParameterValue(9)+0.1)
        
		!Tell the TRNSYS Engine How This Type Works
		Call SetNumberofParameters(9)           !The number of parameters that the the model wants
		!Call SetNumberofInputs(29)                   !The number of inputs that the the model wants
		Call SetNumberofInputs(NumOfInputs)                   !The number of inputs that the the model wants
		!Call SetNumberofInputs(1)                   !The number of inputs that the the model wants
		Call SetNumberofDerivatives(0)         !The number of derivatives that the the model wants
		Call SetNumberofOutputs(0)                 !The number of outputs that the the model produces
		Call SetIterationMode(5)                             !An indicator for the iteration mode (default=1).  Refer to section 8.4.3.5 of the documentation for more details.
		Call SetNumberStoredVariables(0,0)                   !The number of static variables that the model wants stored in the global storage array and the number of dynamic variables that the model wants stored in the global storage array
		Call SetNumberofDiscreteControls(0)               !The number of discrete control functions set by this model (a value greater than zero requires the user to use Solver 1: Powell's method)

        !  Set the Correct Input and Output Variable Types
        if(Num_of_Flow_Control > 0) then
            Do j=1,Num_of_Flow_Control
	           Call SetInputUnits((j-1)*10+1,'NAV')    
            EndDo    
        Endif
        
        !もし既存のControl data fileが存在すれば、削除しておく
        filename = getLUFilename(LU)
        INQUIRE (FILE = filename, EXIST = exists)         
        if(exists) then
          Open (unit=LU,file=filename,action='READ',status='OLD',err=402)
          Close (LU, status='delete', err=403)
#ifdef debug          
          Call Messages(-1,'The existing control file has been deleted.','Notice',CurrentUnit,CurrentType)
#endif            
        endif

        Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the First Timestep Manipulations Here - There Are No Iterations at the Intial Time
      If (getIsStartTime()) Then
        
        Call saveControlFile(CurrentUnit,CurrentType, Time, Timestep)

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!ReRead the Parameters if Another Unit of This Type Has Been Called Last
      If(getIsReReadParameters()) Then
		!Read in the Values of the Parameters from the Input File

        !Get Parameters
        Interval_Time = jfix(getParameterValue(1)+0.1) !control dataの再チェックまでの待機時間[msec]
        StartTime = getParameterValue(2)
        StopTime  = getParameterValue(3)
        LU = jfix(getParameterValue(4)+0.1)
        ! Inputs数を計算
        Num_of_Flow_Control     = JFIX(getParameterValue(5)+0.1) 
        Num_of_Surface_Control  = JFIX(getParameterValue(6)+0.1)  
        Num_of_Volume_Control   = JFIX(getParameterValue(7)+0.1) 
        Num_of_Open_Control     = JFIX(getParameterValue(8)+0.1) 
        NumOfInputs = Num_of_Flow_Control*10 + Num_of_Surface_Control*7 + Num_of_Volume_Control*10 + Num_of_Open_Control*2
        OverwriteFlag           = JFIX(getParameterValue(9)+0.1) 
		
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!Read the Inputs

        


      !Flow_Control_Label = GetInputValue(1)
      !U = GetInputValue(2)
      !V = GetInputValue(3)
      !W = GetInputValue(4)
      !T = GetInputValue(5)
      !Cc = GetInputValue(6)
      !Ch = GetInputValue(7)
      !C1 = GetInputValue(8)
      !C2 = GetInputValue(9)
      !C3 = GetInputValue(10)
      !Surface_Control_Label = GetInputValue(11)
      !Tstar = GetInputValue(12)
      !Mcsurf = GetInputValue(13)
      !Mhsurf = GetInputValue(14)
      !M1surf = GetInputValue(15)
      !M2surf = GetInputValue(16)
      !M3surf = GetInputValue(17)
      !Volume_Control_Label = GetInputValue(18)
      !Q = GetInputValue(19)
      !kx = GetInputValue(20)
      !ky = GetInputValue(21)
      !kz = GetInputValue(22)
      !Mcvol = GetInputValue(23)
      !Mhvol = GetInputValue(24)
      !M1vol = GetInputValue(25)
      !M2vol = GetInputValue(26)
      !M3vol = GetInputValue(27)
      !Open_Control_Label = GetInputValue(28)
      !r = GetInputValue(29)
		
      

      

	!Check the Inputs for Problems (#,ErrorType,Text)
	!Sample Code: If( IN1 <= 0.) Call FoundBadInput(1,'Fatal','The first input provided to this model is not acceptable.')
 
      If(ErrorFound()) Return
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!    *** PERFORM ALL THE CALCULATION HERE FOR THIS MODEL. ***
!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Previous Control States if Discrete Controllers are Being Used (#)
	!Sample Code: CONTROL_LAST=getPreviousControlState(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Values from the Global Storage Array for the Static Variables (#)
	!Sample Code: STATIC1=getStaticArrayValue(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Initial Values of the Dynamic Variables from the Global Storage Array (#)
	!Sample Code: T_INITIAL_1=getDynamicArrayValueLastTimestep(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!Perform All of the Calculations Here to Set the Outputs from the Model Based on the Inputs

	!Sample Code: OUT1=IN1+PAR1

	!If the model requires the solution of numerical derivatives, set these derivatives and get the current solution
	!Sample Code: T1=getNumericalSolution(1)
	!Sample Code: T2=getNumericalSolution(2)
	!Sample Code: DTDT1=3.*T2+7.*T1-15.
	!Sample Code: DTDT2=-2.*T1+11.*T2+21.
	!Sample Code: Call SetNumericalDerivative(1,DTDT1)
	!Sample Code: Call SetNumericalDerivative(2,DTDT2)

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Outputs from this Model (#,Value)

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Desired Disceret Control Signal Values for this Iteration (#,State)
!Sample Code:  Call SetDesiredDiscreteControlState(1,1)
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Final value of the Dynamic Variables in the Global Storage Array (#,Value)
!Sample Code:  Call SetValueThisIteration(1,T_FINAL_1)
!-----------------------------------------------------------------------------------------------------------------------
 
      Return
      
      
      
!-----------------------------------------------------------------------------------------------------------------------
! Error messages
!-----------------------------------------------------------------------------------------------------------------------
! Error found in writing data file
 400  Call Messages(-1,WriteError,'fatal',CurrentUnit,CurrentType) ! control data file書き込み中のエラー
      Return
 !401  Call Messages(-1,EndError,'fatal',CurrentUnit,CurrentType)
 !     Return
 402  Call Messages(-1,FoundError,'fatal',CurrentUnit,CurrentType)
      Return
 403  Call Messages(-1,DeleteError,'fatal',CurrentUnit,CurrentType)
      Return
      
            
      End
!-----------------------------------------------------------------------------------------------------------------------
! イベント処理    
!-----------------------------------------------------------------------------------------------------------------------
SUBROUTINE DoEvents()

use IFWINTY
use USER32
use IFLOGM
logical lNotQuit, lret
integer iret
TYPE (T_MSG) mesg
lNotQuit = .TRUE.
do while (lNotQuit .AND. (PeekMessage(mesg, 0, 0, 0, PM_NOREMOVE) /= 0))
  lNotQuit = GetMessage(mesg, NULL, 0, 0)
    if (lNotQuit) then
      if (DLGISDLGMESSAGE(mesg) .EQV. .FALSE.) then
         lret = TranslateMessage(mesg)
         iret = DispatchMessage(mesg)
      end if
    end if
end do


END SUBROUTINE DoEvents
